# Generated by Django 4.0.4 on 2022-04-23 01:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('out_come', '0001_initial'),
        ('jars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JarOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('jar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='jars.jar')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jars', to='out_come.outcome')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
