# Generated by Django 4.0.4 on 2022-04-23 01:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('in_come', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='in_come.income')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='wallet.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
