# Generated by Django 4.0.4 on 2022-06-07 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('out_come', '0002_outcome_price_outcome_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
