# Generated by Django 4.0.4 on 2022-06-07 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('in_come', '0002_income_price_income_user_alter_income_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
