# Generated by Django 4.0.4 on 2022-06-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usertoken',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
